### ISSUE TITLE
Tokenize card via JSON instead of form

### ISSUE THREAD

**Issue by fortunee** [NutriconsultorOnline/angularjs-conekta#1]
Hi there,
This is my first time using conekta, and my project is based on angularjs and I came across your library which seemed to be the best for my project. 

However, when I try to tokenize a card I'm not actually passing the card details via form I'm using JSON instead and I get the following errors as a result 

`Payment error:  The form or hash has no attributes 'card'.  If you are using a form, please ensure that you have an input or text area with the data-conekta attribute 'card[number]'.`

I'd really appreciate it if I could get a solution to this ASAP. 

Thanks in advance 🙏 

Below is sneak peek to my code: 👇 
```
       const orderPackage = { 
            card: {
            number: paymentMethod.cardNumber,
            name: paymentMethod.cardName,
            exp_year: paymentMethod.expiryYear,
            exp_month: paymentMethod.expiryMonth,
            cvc: paymentMethod.cardCvv
          },
          amount: order.totalPrice,
        };

        return conekta.token.create(orderPackage.card).then((res) => {
          console.log('token created for a card');
          res.amount = order.totalPrice;
          console.log(res);
        }).then(function (payment) {
          console.log('successfully submitted payment for $', payment.amount);
        })
        .catch(function (err) {
          console.log('Payment error: ', err.message);
        });
      };

**Comment by omar10594** [comment]
You only need send an object with card attribute, so instead of `return conekta.token.create(orderPackage.card).then(...);` you should use `return conekta.token.create(orderPackage).then(...);`

**Comment by fortunee** [comment]
Hi @omar10594, thank you very much for your response. 
Now it works but I'm getting an error that says 
`Payment error:  Cannot read property 'amount' of undefined` 
even though I have the amount property defined in my `orderPackage` object.
 I'm not sure I'm passing the right object, could you help me, please?

**Comment by omar10594** [comment]
Because you are trying to set a amount here -> `res.amount = order.totalPrice;`
Conekta only will return the token of the card.

I will close this issue, because there is not a problem with our library.
If you need more help, you can send me an email.
